# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "shanghai"
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.25"
  src = "src"
  test = "test"
  viaIR = true
  libs = ["lib"]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  arbitrum = { key = "${API_KEY_ARBISCAN}" }
  arbitrum-sepolia = { key = "${API_KEY_ARBISCAN}" }
  sepolia = { key = "${API_KEY_ETHERSCAN}" }
  leverabicalight = { key = "${API_KEY_ETHERSCAN}", chain = 109695, url = "https://leverabica.light.rpc.1ok69go.space" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  mainnet = "https://rpc.ankr.com/eth"
  arbitrum = "https://arb1.arbitrum.io/rpc"
  arbitrum-sepolia = "https://arb-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  sepolia = "https://eth-sepolia.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  leverabicalight = "https://leverabica.light.rpc.1ok69go.space"
