services:
  light-nitro-node:
    image: ghcr.io/espressosystems/nitro-espresso-integration/nitro-node:integration
    container_name: light_nitro_node
    ports:
      - '8547:8547'
      - '8548:8548'
      - '8549:8549'
    command: --conf.file /config/full_node.json
    volumes:
      - ./light/config:/config
      - ./light/wasm:/home/user/wasm/
      - ./light/database:/home/user/.arbitrum
    depends_on:
      - light-validation-node
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://logs3.papertrailapp.com:15628'
        tag: '{{.Name}}/{{.ID}}'
        labels: 'group:nitro-node-logs'

  light-validation-node:
    image: ghcr.io/espressosystems/nitro-espresso-integration/nitro-node:integration
    container_name: light_validation_node
    ports:
      - '8949:8549'
    volumes:
      - ./light/config:/config
    entrypoint: /usr/local/bin/nitro-val
    command: --conf.file /config/validation_node_config.json
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://logs3.papertrailapp.com:15628'
        tag: '{{.Name}}/{{.ID}}'
        labels: 'group:validation-node-logs'

  light-caff-node:
    image: ghcr.io/espressosystems/nitro-espresso-integration/nitro-node@sha256:bf63374a00a5d6676ca39af79ac4b0f053128cb7438bcdaa746dba6656c12658
    container_name: light_caff_node
    ports:
      - '8550:8547'
      - '8551:8548'
      - '8552:8549'
    command: --conf.file /config/caff_node.json
    volumes:
      - ./light/config:/config
      - ./light/wasm:/home/user/wasm/
      - ./light/caff-database:/home/user/.arbitrum
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://logs3.papertrailapp.com:15628'
        tag: '{{.Name}}/{{.ID}}'
        labels: 'group:caff-node-logs'
    depends_on:
      - light-nitro-node
